batch_size: 16
checkpoint_path: null
dset_paths:
  - data/real_data/captures/2024-10-23_carter_250
  - data/real_data/captures/2024-10-30_casey_250
  - data/real_data/captures/2024-11-07_alex_250
  - data/real_data/captures/2024-11-07_connor_250
  - data/real_data/captures/2024-11-07_cat_250
epochs: 500
num_cameras: 8
rot_type: 6d
save_model_interval: 50