---
batch_size: 1
dset_path: data/real_data/6d_pose/YCB/cheezits_refined_gt
dset_type: real
include_hist_idxs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]
num_samples_to_vis: 50
obj_path: data/obj_meshes/003_cracker_box/google_16k/nontextured.stl
rot_type: 6d
save_opt: true
sensor_plane_path: data/real_data/6d_pose/YCB/cheezits_refined_gt/001
symmetric_object: true
subsample_n_test_samples: 0 # 0 means do all test samples
test_on_split: all
training_path: 6d_pose_estimation/results/train_hparam_search/train/2025-02-07_10-07-37/013/model_final.pth
opt_params:
  translation_lr: 0.001
  rotation_lr: 0.01
  albedo_obj_lr: 0.01
  opt_steps: 50
  use_lowest: true
  method: random_start # can be fixed, random_start, random_lr, or random_start_random_lr
  num_runs: 10 # the number of optimizations to run - one with lowest loss is selected