---
batch_size: 1
dset_path: data/real_data/6d_pose/two_16_poses_refined_gt
dset_type: real
include_hist_idxs: "all"
num_samples_to_vis: 50
obj_path: data/obj_meshes/two.stl
rot_type: 6d
save_opt: true
sensor_plane_path: data/real_data/6d_pose/two_16_poses_refined_gt/001
subsample_n_test_samples: 0 # 0 means do all test samples
symmetric_object: false
test_on_split: all
training_path: 6d_pose_estimation/results/train/pt_sim_two_50000/model_499.pth