---
batch_size: 1
dset_path: data/sim_data/6d_pose/colored2_50000/
dset_type: sim
include_hist_idxs: "all"
num_samples_to_vis: 0
obj_path: data/obj_meshes/two.stl
rot_type: 6d
save_opt: true
sensor_plane_path: data/real_data/6d_pose/colored_twos/glossy_white_refined_gt/001
subsample_n_test_samples: 100
test_on_split: test
training_path: 6d_pose_estimation/results/train/pt_sim_colored2_50000/model_499.pth