dset_path: data/sim_data/6d_pose/two_50000/simulated_data.npz
training_path: 6d_pose_estimation/results/train/pt_sim_two_50000
batch_size: 2048
rot_type: 6d
save_opt: True
obj_path: data/obj_meshes/two.stl
dset_type: "sim"