dset_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/6d_pose_estimation/data/sim_data/6d_pose/2024-12-25_object_on_surface_50000_noise_preprocess/simulated_data.npz
training_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/6d_pose_estimation/results/train/pt_sim_2025-01-06 02:25:14.550593
batch_size: 2048
rot_type: 6d
checkpoint_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/6d_pose_estimation/results/train/pt_sim_2025-01-06 02:25:14.550593/model_final.pth
save_opt: True
obj_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/data/obj_meshes/two.stl


