---
batch_size: 2048
dset_path: data/sim_data/6d_pose/two_50000/simulated_data.npz
dset_type: sim
obj_path: data/obj_meshes/two.stl
rot_type: 6d
save_opt: true
training_path: 6d_pose_estimation/results/train/pt_sim_two_50000