---
batch_size: 1
dset_path: data/real_data/6d_pose/colored_twos/glossy_white_refined_gt
dset_type: real
include_hist_idxs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]
num_samples_to_vis: 50
obj_path: data/obj_meshes/two.stl
rot_type: 6d
save_opt: true
sensor_plane_path: data/real_data/6d_pose/colored_twos/glossy_white_refined_gt/001
subsample_n_test_samples: 0 # 0 means do all test samples
symmetric_object: false
test_on_split: all
training_path: 6d_pose_estimation/results/train/pt_sim_colored2_50000_15cam/model_499.pth
opt_params:
  translation_lr: 0.001
  rotation_lr: 0.01
  albedo_obj_lr: 0.01
  opt_steps: 100