dset_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/6d_pose_estimation/data/sim_data/6d_pose/2024-12-25_object_on_surface_50000_noise_preprocess/simulated_data.npz
epochs: 1000
batch_size: 2048
save_model_interval: 50
rot_type: 6d
obj_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/data/obj_meshes/two.stl
check_real: True
real_path: /home/yiquan/spad_hand_carter/SPAD_HAND__Carter/data/two_16_poses_real







