---
batch_size: 2048
check_real: true
dset_path: data/sim_data/6d_pose/cheezits_50000/simulated_data.npz
dset_type: sim
epochs: 1000
include_hist_idxs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]
loss_type: "ADD_S"
mesh_sample_count: 500
noise_level: 0
normalize_hist_peaks: true
normalize_hists: false
obj_path: data/obj_meshes/003_cracker_box/google_16k/nontextured.stl
real_path: data/real_data/6d_pose/YCB/cheezits_refined_gt
rot_type: 6d
save_model_interval: 50
standardize_input: false
subtract_dc_offset_from_real: true
symmetric_object: true
trim_to_range:
- 0
- 128